#!/usr/bin/env bash
# Bassh script that transfer file to our server usig the SCP
if [[ $# < 3 ]];
then
   echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
   scp "$1" "$3@$2:$4" 
fi 
