#!/usr/bin/env bash
#Bash script that loops from 1 to 10 and
#+ displays "bad luck" for the 4th loop iteration
#+ displays "good luck" for the 8th loop iteration
#+ displays "Best School for the other iterations

var="Best School"
var1="bad luck"
var2="good luck"
a=1

while [[ $a -le 10 ]]
do
    if [[ $a -eq 4 ]]
    then
        echo "$var1"
    elif [[ $a -eq 8 ]]
    then
        echo "$var2"
    else
        echo "$var"
    fi

    (( a++ ))
done
