#!/usr/bin/env bash

#This is a Bash script that displays numbers from 1 to 20 and:
#+ displays 4 and then "bad luck from China" for the 4th loop iteration
#+ displays 9 and then "bad luck from Japan" for the 9th loop iteration
#+ displays 17 and then "bad luck from Italy" for the 17th loop iteration

var1="bad luck from China"
var2="bad luck from Japan"
var3="bad luck from Italy"
a=1

while [[ $a -le 20 ]]
do
	if [[ $a -eq 4 ]]
	then
		echo "4"
		echo "$var1"
    	elif [[ $a -eq 9 ]]
    	then
		echo "9"
        	echo "$var2"
    	elif [[ $a -eq 17 ]]
    	then
        	echo "17"
		echo "$var3"
	else
		echo "$a"
    	fi
   
	(( a++ ))
done
